<?php

namespace App\Models;

use App\Message;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    const SH = 'sh';
    const RH = 'rh';
    const All = 'all';

    protected $table = 'notifications';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    protected $fillable = ["id", "message", "receiver", "created_at", "updated_at"];
    // protected $hidden = [];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */
    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::created(function($notification){

            switch ($notification->receiver){
                case Notification::RH:
                    $users = User::where("role", \App\User::RH)->get();
                    break;
                case Notification::SH:
                    $users = User::where("role", \App\User::SH)->get();
                    break;
                default:
                    $users = User::all();
                    break;
            }

            foreach($users as $user){
                foreach ($user->hosts as $receiver){
                    $message = new Message([
                        "host_id" => $receiver->id,
                        "notification_id" => $notification->id,
                    ]);

                    $message->save();
                }
            }

        });
    }


    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    public function messages(){
        return $this->hasMany("\App\Message", "notification_id");
    }

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}
